config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'trainings#show'
  resources :trainings, only: %i[index]
  resources :plans, only: %i[index show] do
    resources :trainings, only: %i[show]
  end
  namespace :admin do
    resources :trainings, only: %i[new update destroy]
    resources :plans, only: %i[new update destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :trainings
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :plan
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
  end

  def show
    @trainings = Plan.all.map do |plan|
      plan.trainings.where("date >= ?", Date.today).order("date ASC").limit(1)[0]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Entrainements du jour</h1>
<div class="container">
  <% @trainings.each do |training| %>
  <div class="card" style="width: 18rem;">
<div class="card-body">
  <h5 class="card-title">Plan <%= training.plan.name %></h5>

  <p class="card-text"><%= training.description %></p>
  <a href="#" class="card-link">Card link</a>
  <a href="#" class="card-link">Another link</a>
</div>
</div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-bottom">
  <%= link_to root_path, class: "nav-link" do %>
    <i class="fas fa-2x fa-running"></i>
  <% end %>

  <%= link_to trainings_path, class: "nav-link" do %>
    <i class="fas fa-2x fa-list-ul"></i>
  <% end %>

  <%= link_to '#', class: "nav-link" do %>
    <i class="fas fa-2x fa-calendar-plus"></i>
  <% end %>

  <% if current_user %>
    <%= link_to '#', method: :delete, class: "nav-link" do %>
      <i class="fas fa-2x fa-sign-out-alt"></i>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path, class: "nav-link" do %>
      <i class="fas fa-2x fa-user"></i>
    <% end %>
  <% end %>
</div>

app/views/trainings/index.html.erb
<div class="container">
  <h2>Entrainements</h2>
  <%= @trainings.each do |training| %>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">Plan <%= training.plan.name %></h5>
      <p class="card-text"><%= training.description %></p>
      <a href="#" class="card-link">Card link</a>
      <a href="#" class="card-link">Another link</a>
    </div>
  </div>
  <% end %>
</div>

app/views/trainings/show.html.erb
<div class="row bg-primary">
  <h1>Aujourd'hui</h1>
</div>
<div class="row">

</div>

<div class="container">
  <% @trainings.each do |training| %>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">Plan <%= training.plan.name %></h5>
      <p class="card-text"><%= training.description %></p>
      <a href="#" class="card-link">Card link</a>
      <a href="#" class="card-link">Another link</a>
    </div>
  </div>
  <% end %>
</div>